name: Run Python Script
on: [push]
jobs:
    run-python-script:
        runs-on: ubuntu-latest
        steps:
            - name: Inicio
              run: echo "Comienza Action"
            - name: Clona repo
              uses: actions/checkout@v6   
            - name: Muestra archivos
              run: ls -al
            - name: Definir variable
              run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
            - name: Ejecuta el script
              run: python app.py